version: '3'

services:
  nginx:
    container_name: Inception_Nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - my_network
    volumes:
      - wordpress:/var/www/html
    restart: always

  wordpress:
    container_name: Inception_Wordpress
    build:
      context:  ./requirements/wordpress
    networks:
      - my_network
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    environment: 
      MYSQL_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
    restart: always

  mariadb:
    container_name: Inception_Mariadb
    build:
      context:  ./requirements/mariadb
    networks:
      - my_network
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    restart: always

networks:
  my_network:
    driver: bridge

volumes:
  wordpress:
  wordpress_db:
