version: '3'

# # Each service has its own build context, restart policy, and network configuration.

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - my_network

# # The WordPress service depends on a custom build context and has associated volumes for database and website files.
  wordpress:
    build:
      context:  ./requirements/wordpress
    restart: always
    networks:
      - my_network
    volumes:
      - wordpress_db:/var/lib/mysql
      - wordpress_files:/var/www/html


# # The MariaDB service depends on a custom build context and has an associated volume for the WordPress database.
  mariadb:
    build:
      context:  ./requirements/mariadb
    restart: always
    networks:
      - my_network
    volumes:
      - wordpress_db:/var/lib/mysql


# # Define a custom bridge network named "my_network" for inter-container communication.
networks:
  my_network:
    driver: bridge


# # Define two volumes named "wordpress_db" and "wordpress_files" for persistent storage.
volumes:
  # mariadb:
  #   name: mariadb
  #   driver: local
  #   driver_opts:
  #     device: 
  #     o: bind
  #     type: none

  wordpress_db:
  wordpress_files:
