version: "sheree's magical version of inception"

name: inception

services:
  nginx:
    ports:
      - "443:443"
    image: nginx
    container_name: nginx_c
    build: ./requirements/nginx
    networks:
      - mynetwork
    restart: always
    volumes:
      - wordpress-data:/var/www/html

  mariadb:
    image: mariadb
    container_name: mariadb_c
    build: 
      context: ./requirements/mariadb
    networks:
      - mynetwork
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file: .env
  wordpress:
    image: wordpress
    container_name: wordpress_c
    build: 
      context: ./requirements/wordpress
    networks:
      - mynetwork
    restart: always
    volumes:
      - wordpress-data:/var/www/html
    env_file: .env
    
volumes:
  mariadb-data:
    driver: local
    driver_opts:
      device: /home/smorphet/data/mariadb-data
      o: bind
      type: none
  wordpress-data:
    driver: local
    driver_opts:
      device: /home/smorphet/data/wordpress-data
      o: bind
      type: none

networks:
  mynetwork:
    name: mynetwork
